# Generated by Django 4.2.23 on 2025-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_loanaccount_expensecategory_is_loan_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
