# Generated by Django 4.2.23 on 2025-08-30 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0004_expense_is_favourite_income_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock / ETF'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond'), ('mmf', 'Money Market Fund'), ('real_estate', 'Real Estate'), ('sacco', 'SACCO / CHAMA'), ('other', 'Other')], max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('units_held', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coupon_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_so_far', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('expenses_so_far', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('is_callable', models.BooleanField(default=False)),
                ('interest_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('base_date', models.DateField(blank=True, null=True)),
                ('sacco_capital_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sacco_minimum_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sacco_total_contributions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('sacco_contribution_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('sacco_dividend_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('sacco_dividends_earned', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.investmentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('RENTAL', 'Rental Income'), ('EXPENSE', 'Expense'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('CAPITAL_SHARE', 'Capital'), ('CONTRIBUTION', 'Contribution')], max_length=20)),
                ('units', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.investmentaccount')),
                ('linked_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.expense')),
                ('linked_income', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.income')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.expensesource')),
            ],
        ),
    ]
