# Generated by Django 4.2.23 on 2025-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_investmentaccount_pricehistory_investmenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='is_investment_generated',
            field=models.BooleanField(default=False),
        ),
    ]
