# Generated by Django 4.2.23 on 2025-08-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_expensecategory_is_investment_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='is_investment_generated',
            field=models.BooleanField(default=False),
        ),
    ]
