# Generated by Django 4.2.23 on 2025-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_investmenttransaction_is_investment_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
