# Generated by Django 4.2.23 on 2025-10-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0010_userhiddensubcategory_userhiddenincomesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHiddenWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.expensesource')),
            ],
            options={
                'unique_together': {('user', 'wallet')},
            },
        ),
    ]
